README.md, components/vaultAssetRow/vaultAssetRow.js, components/vaultAssetRow/vaultAssetRow.module.css, pages/invest/index.js, pages/invest/invest.module.css
use materialui Table element for /invest
makes it possible to filter by table column
=> Invest table

README.md
Added a section to explain how to set infura and etherscan keys.
=> add getting started section to README.md

.prettierignore, .prettierrc, components/vaultAssetRow/vaultAssetRow.js, pages/invest/index.js, stores/index.js, stores/investStore.jsx
This is about this issue #8 
Test deploy here: https://yearn-finance-1-1bo9vvo0k-patcito.vercel.app/
more info on the API here:
https://docs.zapper.fi/build/zapper-api#authentication
https://docs.zapper.fi/build/guides/yearn-user-balances
It also replaces coingecko by zapper api so it saves about +52 XHR calls on load.
=> show missing balance using zapper public API

components/simulation/package.json, components/simulation/simulation.js, components/simulation/simulation.module.css, components/vaultActionCard/deposit.js, package.json, pages/invest/[address]/index.js
it's possible to modify params (apy, token pricem years) to give the user an idea of how much could make.
You can try it deployed here https://yearn-finance-1-git-invest-simulation-patcito.vercel.app/
=> add a simulation card to show how much one can make with a vault

components/header/aboutModal.js, components/header/header.js, components/simulation/simulation.js
The current homepage can be a bit intimidating specially for noobs so added a "what is yearn button" in the header.
- if metamask is installed it shows a more technical description first and the button says "but ser?" (saw this on alchimix and thought it was funny)
- if metamask is not detected it shows a more newbie friendly introduction and the button says "what is yearn?"
Deployed here https://yearn-finance-1-c35mnr38s-patcito.vercel.app/
=> What is yearn modal

components/simulation/simulation.js, pages/invest/index.js, pages/invest/invest.module.css
inspired by this tweet https://twitter.com/iearnfinance/status/1375466910385586186
current heuristic for stablecoins is to check that the price of the token is between 0.9 and 1.4. The alternative would be to hard code each vault address.
Deployed here https://yearn-finance-1-hwqmto8xx-patcito.vercel.app/
=> show and filter by top performers on top of /invests

components/vaultActionCard/deposit.js, stores/investStore.jsx
sending fixes to the zap-on-invest branch here
deployed: https://yearn-finance-1-git-zap-on-invest-fixes-patcito.vercel.app/invest/0x5f18C75AbDAe578b483E5F43f12a39cF75b973a9
=> fixes to the zap branch

stores/investStore.jsx
deployed here https://yearn-finance-1-git-zap-out-on-withdraw-patcito.vercel.app/
=> always check for approval on zap withdrawal (fixes #23)

components/vaultActionCard/deposit.js, components/vaultActionCard/vaultActionCard.module.css, components/vaultActionCard/withdraw.js, stores/investStore.jsx
implements custom slippage on deposit and withdrawals
=> allow custom zapper slippage (fixes #21)

components/vaultStrategyCard/vaultStrategyCard.js
yvBOOST vault + strat is now deployed and endorsed.
=> Add yvBOOST strategy description

pages/ltv/index.js
use autocomplete to improve UX on /ltv
deployed here https://yearn-finance-1-git-autocomplete-ltv-patcito.vercel.app/
=> use AutoComplete for /ltv select asset

components/header/aboutModal.js, components/header/header.js, components/header/searchModal.js, components/lendAllAssetRow/lendAllAssetRow.js, package-lock.json, package.json, pages/lend/index.js, pages/ltv/index.js, pages/redirect.js, pages/stats/index.js
instant search box through all vaults and assets. Takes you to the vault directly so you can ape as fast as possible.
Just hit Cmd+k or /
https://user-images.githubusercontent.com/26435/114303332-dfe17500-9acd-11eb-872c-2b97efcfc515.mp4
=> Autocomplete instant search box

components/header/header.js, components/header/header.module.css, package-lock.json, pages/invest/index.js, pages/invest/invest.module.css
Improving some slight UI features:
- Search bar shortcut style
- Dark mode switch style
- Home leaderboards style
Search bar and dark toggle (before, after):
Leaderboards (before, after): 
Rationale:
Lighter fonts and sizes render better with the whole site and experience.
=> UI-enhancements

pages/_app.js, pages/cdp/index.js, pages/configure/index.js, pages/home.js, pages/invest/[address]/index.js, pages/invest/index.js, pages/lend/index.js, pages/ltv/index.js, pages/redirect.js, pages/stats/index.js
Fixes linter no-unused-vars mainly and removes some other dead code.
=> :rotating_light: Housekeeping (unused variables)

pages/invest/index.js
- introduces a `Podium` component
- reuses `vaultSort` function
- drops commented out code
=> :recycle: Invest component minor refactoring (DRY)

pages/home.js, pages/invest/index.js, pages/landing/index.js
=> :fire: Drops unused code and fixes linting

components/vaultActionCard/withdraw.js
add withdrawal fee amount under withdraw
see: todos
=> feat: add withdrawal fee

components/vaultActionCard/deposit.js, stores/constants/constants.js
=> fix: disable zap in for yvBOOST vault

components/lendSupplyGraph/lendSupplyGraph.js, components/navigation/navigation.js, components/navigation/navigation.module.css, components/vaultAssetRow/vaultAssetRow.module.css, components/vaultCard/vaultCard.js, components/vaultCard/vaultCard.module.css, components/vaultGrowthNumbers/vaultGrowthNumbers.module.css, components/vaultSplitGraph/vaultSplitGraph.js, components/vaultSplitGraph/vaultSplitGraph.module.css, package-lock.json, package.json, pages/cdp/cdp.module.css, pages/cdp/index.js, pages/invest/[address]/vault.module.css, pages/invest/index.js, pages/invest/invest.module.css, pages/landing/index.js, pages/landing/landing.module.css, pages/lend/lend.module.css, pages/ltv/index.js, pages/ltv/ltv.module.css, pages/stats/index.js, pages/stats/stats.module.css
=> Front end update

components/exploreVaultStrategy/exploreVaultStrategy.js, components/exploreVaultStrategy/exploreVaultStrategy.module.css, components/header/header.js, components/header/header.module.css, components/systemAssetsGraph/systemAssetsGraph.module.css, components/systemFilters/systemFilters.module.css, components/systemProtocolsGraph/systemProtocolsGraph.module.css, components/systemStrategiesGraph/systemStrategiesGraph.module.css, components/systemVaultsGraph/systemVaultsGraph.module.css, pages/cdp/cdp.module.css, pages/system/index.js, pages/system/system.module.css, pages/system/vault/[address]/index.js, pages/system/vault/[address]/system.module.css
Stats layout styling adjustments
=> Stats layout styling adjustments
